version: '3.9'

services:
  sales_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sales_db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sales@2025#!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d
    
  sales_db_init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sales_db_init
    depends_on:
      - sales_db
    entrypoint: >
      /bin/bash -c "
        echo 'â³ Aguardando SQL Server subir...';
        sleep 20;
        echo 'ğŸš€ Executando script inicial...';
        /opt/mssql-tools/bin/sqlcmd -S sales_db -U sa -P sales@2025#! -i /scripts/init.sql;
        echo 'âœ… Script rodado com sucesso!';
      "
    volumes:
      - ./init-db:/scripts

volumes:
  sql_data:
